### PR TITLE
Add Toaster and fix minor bugs

### LINKED ISSUE #95: Replace alert() with Toaster

### PR DESCRIPTION
**Pull request by ketphan02**
+ Close #95 
+ Remove all alerts with [`react-hot-toaster`](https://react-hot-toast.com)
+ Fix minor bugs about optional
+ Pretify the code

### CODE REVIEW

File: src/components/App/PuzzleGenerate/index.tsx [hunk 1]
```diff
@@ -1,31 +1,41 @@
...
+      );
+
+      if (puzzleInstance.error) {
+        throw new Error(puzzleInstance.message);
+      } else {
+        setPuzzleInstanceData(puzzleInstance);
+      }
+    };
+    toast.promise(puzzleInstancePromise(), {
+      loading: 'Hello',
```
Comment (Opeyem1a) [inline src/components/App/PuzzleGenerate/index.tsx:35]: Hello?

File: src/components/App/PuzzleGenerate/index.tsx [hunk 2]
```diff
@@ -87,6 +97,7 @@ const PuzzleGenerate = ({ puzzlesList }) => {
             arrowDirection="right"
             onClick={() => handleSubmit()}
           />
+          <Toaster />
```
Comment (Opeyem1a) [inline src/components/App/PuzzleGenerate/index.tsx:100]: Don't we put this in _document or _page?

File: src/pages/auth/signup/index.tsx [hunk 3]
```diff
@@ -13,17 +14,48 @@ const SignUpPage = () => {
...
+        }
       );
-      event.preventDefault();
       return false;
     }
     if (status === 'authenticated') {
-      if (confirm('Would you like to make another account?'))
-        alert('Please log out before you make an other account.');
-      event.preventDefault();
+      toast(t => (
```
Comment (Opeyem1a) [inline src/pages/auth/signup/index.tsx:29]: Are you sure this implementation replaces the `confirm()` call above?

File: src/pages/puzzles/[instanceId]/index.tsx [hunk 4]
```diff
@@ -38,42 +41,63 @@ const PuzzlePage = ({
...
+            throw new Error('Almost there! Try Again');
+          }
+        }
+      };
 
-      setIsRecentCorrect(success);
-      setFeedbackGifSrc(getRandomGifSrc(feedbackGifs, success));
+      toast.promise(submissionInstance(), {
+        loading: 'Submitting your answer... ⏳',
+        success: 'Correct! Nice work!',
```
Comment (Opeyem1a) [inline src/pages/puzzles/[instanceId]/index.tsx:74]: It seems weird to throw an error for incorrect answers - isn't there a way to grab whatever the promise returns and check `isCorrect`?

File: src/pages/puzzles/[instanceId]/index.tsx [hunk 5]
```diff
@@ -38,42 +41,63 @@ const PuzzlePage = ({
...
+        </span>
+      ));
       // TODO: should be an alert dialog w/ link to login page
     }
   };
 
   return (
     <>
       <Header />
+      <Toaster />
```
Comment (Opeyem1a) [inline src/pages/puzzles/[instanceId]/index.tsx:100]: Yeah I don't think we need to put this tag in multiple places

**Review by Opeyem1a — CHANGES_REQUESTED** [review]

File: src/components/App/PuzzleGenerate/index.tsx (hunk 1 above)
Comment (ketphan02) [reply src/components/App/PuzzleGenerate/index.tsx:35]: Oops 🥲

File: src/pages/puzzles/[instanceId]/index.tsx (hunk 4 above)
Comment (ketphan02) [reply src/pages/puzzles/[instanceId]/index.tsx:74]: I did try to use the hooks approach but somehow toast does not get the update from `useState`.
Normally, I will have `const [errMsg, setErrMsg] = useState<string>();` and then change it according to the cases. But for toast, it doesn't get the update from `setErrMsg` and will fail to send the message. So I think of this solution.
If you think of a better way, please tell me, I know this is an awful implementation 🥺

File: src/components/App/PuzzleGenerate/index.tsx [hunk 6]
```diff
@@ -1,31 +1,41 @@
...
+      if (puzzleInstance.error) {
+        throw new Error(puzzleInstance.message);
+      } else {
+        setPuzzleInstanceData(puzzleInstance);
+      }
+    };
+    toast.promise(puzzleInstancePromise(), {
+      loading: 'Making your puzzle instance... ⚙️',
+      success: 'Success',
+      error: 'Something went wrong :('
```
Comment (Opeyem1a) [inline src/components/App/PuzzleGenerate/index.tsx:37]: Is there at least a way to display the actual message from the error and not just the default string here?

File: src/components/App/PuzzleGenerate/index.tsx [hunk 7]
```diff
@@ -1,31 +1,41 @@
...
+      );
+
+      if (puzzleInstance.error) {
+        throw new Error(puzzleInstance.message);
+      } else {
+        setPuzzleInstanceData(puzzleInstance);
+      }
+    };
+    toast.promise(puzzleInstancePromise(), {
+      loading: 'Making your puzzle instance... ⚙️',
```
Comment (Opeyem1a) [inline src/components/App/PuzzleGenerate/index.tsx:35]: Should this auto-dismiss after a period of time?

File: src/pages/puzzles/[instanceId]/index.tsx [hunk 8]
```diff
@@ -38,35 +41,55 @@ const PuzzlePage = ({
...
+          user
+        );
 
-      if ((submission as HandledError).error) {
-        // TODO: handle errors from submitting
-        alert(submission.message);
-        return;
-      }
+        if ((submission as HandledError).error) {
+          console.error((submission as HandledError).message);
```
Comment (Opeyem1a) [inline src/pages/puzzles/[instanceId]/index.tsx:54]: console?

File: src/pages/puzzles/[instanceId]/index.tsx (hunk 4 above)
Comment (Opeyem1a) [reply src/pages/puzzles/[instanceId]/index.tsx:74]: But does this work? Did you test that it does what you think it does in every case?

File: src/pages/puzzles/[instanceId]/index.tsx [hunk 9]
```diff
@@ -38,35 +41,55 @@ const PuzzlePage = ({
...
+        loading: 'Submitting your answer... ⏳',
+        success: 'Correct! Nice work!',
+        error: err => {
+          return err.message;
+        }
+      });
     } else {
-      alert('You must be logged in to submit puzzles!');
+      toast.error(t => (
+        <span>
```
Comment (Opeyem1a) [inline src/pages/puzzles/[instanceId]/index.tsx:81]: Yeah idk how I feel about having a bunch of custom HTML, can't we make components to put inside this? And just have a few different types of toast components

**Review by Opeyem1a — CHANGES_REQUESTED** [review]

File: src/components/App/PuzzleGenerate/index.tsx (hunk 7 above)
Comment (ketphan02) [reply src/components/App/PuzzleGenerate/index.tsx:35]: `toast.promise` will automatically change to success or fail

File: src/pages/puzzles/[instanceId]/index.tsx (hunk 8 above)
Comment (ketphan02) [reply src/pages/puzzles/[instanceId]/index.tsx:54]: i think instead of sending the error through toaster for the end-user, I think it's better to send to console (`console.error` will send a message with error format so it's easy to identify)

File: src/pages/puzzles/[instanceId]/index.tsx (hunk 9 above)
Comment (ketphan02) [reply src/pages/puzzles/[instanceId]/index.tsx:81]: i'll do that!

**Comment by ketphan02** [comment]
Use on top right

File: src/pages/puzzles/[instanceId]/index.tsx (hunk 8 above)
Comment (Opeyem1a) [reply src/pages/puzzles/[instanceId]/index.tsx:54]: But how would the user see the `console.error()`, wouldn't they have to already have developer tools open to see it?

**Review by Opeyem1a — APPROVED** [review]
This seems fine now - just grab me some images of what it looks like @ketphan02

**Comment by ketphan02** [comment]
@Opeyem1a

https://user-images.githubusercontent.com/35695324/152636429-4740be90-6fb7-4afa-adff-cfb6b5aadf45.mov


https://user-images.githubusercontent.com/35695324/152636488-9eba9dcd-75ae-4d7e-8a44-f78b690101bf.mov

**Comment by Opeyem1a** [comment]
Looks good!
